parameters:
    euwarning.stylesheet: null

services:
    zikula_legal_module.container.link_container:
        class: Zikula\LegalModule\Container\LinkContainer
        arguments:
          - "@translator.default"
          - "@jms_i18n_routing.router"
          - "@zikula_permissions_module.api.permission"
          - "@zikula_extensions_module.api.variable"
        tags:
            - { name: zikula.link_container }

    twig.extension.zikula_legal_module:
        class: Zikula\LegalModule\Twig\TwigExtension
        public: false
        arguments: ["@twig"]
        tags:
            - { name: twig.extension }

    zikula_legal_module.event_listener:
        class: Zikula\LegalModule\Listener\UsersUiListener
        arguments:
          - "@request_stack"
          - "@twig"
          - "@translator.default"
          - "@jms_i18n_routing.router"
          - "@zikula_core.common.csrf_token_handler"
          - "@zikula_users_module.current_user"
          - "@zikula_legal_module.accept_policies_helper"
          - "@=service('zikula_extensions_module.api.variable').getAll('ZikulaLegalModule')"
          - "@form.factory"
          - "@doctrine"
        tags:
            - { name: kernel.event_subscriber }

    zikula_legal_module.eu_warning_listener:
        class: Zikula\LegalModule\Listener\EuCookieWarningInjectorListener
        arguments:
          - "@router"
          - "@zikula_core.common.theme.asset_helper"
          - "%euwarning.stylesheet%"
          - "@zikula_theme_module.api.page_asset"
          - "@=service('zikula_extensions_module.api.variable').get('ZikulaLegalModule', 'eucookie', 0)"
        tags:
            - { name: kernel.event_subscriber }

    zikula_legal_module.accept_policies_helper:
        class: Zikula\LegalModule\Helper\AcceptPoliciesHelper
        arguments:
          - "@zikula_permissions_module.api.permission"
          - "@zikula_users_module.current_user"
          - "@zikula_users_module.user_repository"
          - "@=service('zikula_extensions_module.api.variable').getAll('ZikulaLegalModule')"

    zikula_legal_module.reset_agreement_helper:
        class: Zikula\LegalModule\Helper\ResetAgreementHelper
        arguments:
          - "@zikula_users_module.user_attribute_repository"
          - "@zikula_groups_module.group_repository"
          - "@zikula_permissions_module.api.permission"
